spring:
  datasource:
    hikari:
      maximumPoolSize: 5
    url: ENC("@db.url@")
    username: ENC("@db.username@")
    password: ENC("@db.password@")

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC("0JCgrd639iwkK+/GgXZVMFZfmnPJZRusFI/DxhHq0Zo303BUpwnALg==")
    password: ENC("YBVpp0UnXh3IHJ4DjkgTSONKyiQezTaF")
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logback:
  dir: "/usr/local/tomcat8/logs"
  level: "DEBUG"

